version: '3.8'
services:
  game-api:
    build: "/"
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    command: >
      sh -c "dos2unix mvnw &&
             ./mvnw spring-boot:run"